<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

/**
 * Simple autoloader, so we don't need Composer just for this.
 */
class Autoloader
{
    public static function register()
    {
        spl_autoload_register(function ($class) {
            $file = 'clasess/' . str_replace('\\', DIRECTORY_SEPARATOR, $class) . '.php';
            $file_controler =  'clasess/controler/' . str_replace('\\', DIRECTORY_SEPARATOR, $class) . '.php';
            $file_alt =  '../clasess/' . str_replace('\\', DIRECTORY_SEPARATOR, $class) . '.php';
            if (file_exists($file)) {
                require $file;
                return true;
            } else {
                if (file_exists($file_controler)) {
                    require $file_controler;
                    return true;
                } else {
                    if (file_exists($file_alt)) {
                        require $file_alt;
                        return true;
                    } else {
                        return false;
                    }
                }
            }
            return false;
        });
    }
}
Autoloader::register();

return ComposerAutoloaderInit728f96e67824ff0c88d9b31fcd5c7681::getLoader();
